import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/layout/Nav/Nav";
import DarkModeToggle from "@/components/layout/DarkModeToggle";
import FixedTop from "@/components/layout/FixedTop";
import ContentBox from "@/components/layout/ContentBox";

import { config, dom } from "@fortawesome/fontawesome-svg-core";
import Head from "next/head";
import Footer from "@/components/layout/Footer";
config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${inter.className} bg-bgLight dark:bg-bgDark text-black dark:text-white`}
      >
        {/* font awesome icons are loading large because font awesome css is not loading
        this block adds font awesome css */}
        <Head>
          <style>{dom.css()}</style>
        </Head>

        <FixedTop className="flex items-center gap-10">
          <Nav />
        </FixedTop>

        <ContentBox>{children}</ContentBox>
      </body>
    </html>
  );
}
