import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/layout/Nav";
import DarkModeToggle from "@/components/layout/DarkModeToggle";
import FixedTop from "@/components/layout/FixedTop";
import ContentBox from "@/components/layout/ContentBox";
import Footer from "@/components/layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${inter.className} bg-bgLight dark:bg-bgDark text-black dark:text-white`}
      >
        <FixedTop className="flex items-center gap-10">
          <Nav />
          <DarkModeToggle />
        </FixedTop>

        <ContentBox>{children}</ContentBox>
      </body>
    </html>
  );
}
